[build]
command = "yarn build"
publish = ".next"

[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/.netlify/functions/test-handler"
status = 200

[dev]
framework = "#static"

[functions]

[functions.test-handler]
node_bundler = "nft"
included_files = [".next/server/**", ".next/*.json", ".next/BUILD_ID"]
