[build]
command = "yarn build"
publish = ".next"

[[redirects]]
from = "/*"
to = "/.netlify/functions/test-handler"
status = 200

[dev]
framework = "#static"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]

[functions.test-handler]
node_bundler = "nft"
included_files = [".next/server/**", ".next/*.json", ".next/BUILD_ID"]
